#!/usr/bin/env python3
"""Build public Markdown pages from canonical song records and snapshots."""

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import tomllib

ROOT = Path(__file__).resolve().parents[1]
GENERATED = "<!-- Generated by scripts/build.py from canonical CREDITS.toml records. Do not edit directly. -->"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_entries():
    entries = []
    for record in sorted((ROOT / "songs").glob("*/inputs/CREDITS.toml")):
        data = tomllib.loads(record.read_text())
        data.update(data.pop("work"))
        input_directory = record.parent
        directory = input_directory.parent
        source_ids = {source["id"] for source in data["sources"]}
        artifact_ids = {artifact["id"] for artifact in data["artifacts"]}
        for artifact in data["artifacts"]:
            path = input_directory / artifact["file"]
            if digest(path) != artifact["sha256"]:
                raise SystemExit(f"checksum mismatch: {path.relative_to(ROOT)}")
            if artifact["acquired_from"] not in source_ids:
                raise SystemExit(f"unknown source for {artifact['id']}: {artifact['acquired_from']}")
            if artifact.get("derived_from") not in (None, *artifact_ids):
                raise SystemExit(f"unknown parent artifact for {artifact['id']}: {artifact['derived_from']}")
            if artifact.get("derived_from") == artifact["id"]:
                raise SystemExit(f"artifact cannot derive from itself: {artifact['id']}")
        for edition in data.get("score_editions", []):
            if edition["source"] not in source_ids:
                raise SystemExit(f"unknown score edition source: {edition['source']}")
            unknown = set(edition["artifacts"]) - artifact_ids
            if unknown:
                raise SystemExit(f"unknown score edition artifact(s): {', '.join(sorted(unknown))}")
        for arrangement in data.get("arrangements", []):
            if arrangement["source"] not in source_ids:
                raise SystemExit(f"unknown arrangement source: {arrangement['source']}")
            unknown = set(arrangement["artifacts"]) - artifact_ids
            if unknown:
                raise SystemExit(f"unknown arrangement artifact(s): {', '.join(sorted(unknown))}")
        for work in data.get("creative_commons_works", []):
            if work["source"] not in source_ids:
                raise SystemExit(f"unknown Creative Commons source: {work['source']}")
            referenced = set(work["files"]) | set(work.get("images", []))
            if work.get("audio"):
                referenced.add(work["audio"])
            unknown = referenced - artifact_ids
            if unknown:
                raise SystemExit(f"unknown Creative Commons artifact(s): {', '.join(sorted(unknown))}")
        for fact in data["facts"]:
            unknown = set(fact["sources"]) - source_ids
            if unknown:
                raise SystemExit(f"unknown fact source(s): {', '.join(sorted(unknown))}")
        listening_urls = data.get("listening", {}).get("urls", [])
        listening_labels = data.get("listening", {}).get("labels", [])
        if len(listening_urls) != len(set(listening_urls)):
            raise SystemExit(f"duplicate listening URL in {record.relative_to(ROOT)}")
        if len(listening_urls) != len(listening_labels):
            raise SystemExit(f"listening labels and URLs differ in length in {record.relative_to(ROOT)}")
        if any(not url.startswith("https://archive.org/details/") for url in listening_urls):
            raise SystemExit(f"non-Archive.org listening URL in {record.relative_to(ROOT)}")
        for recording in data.get("reviewed_recordings", []):
            if recording["source"] not in source_ids:
                raise SystemExit(f"unknown reviewed recording source: {recording['source']}")
            if recording.get("local_artifact") and recording["local_artifact"] not in artifact_ids:
                raise SystemExit(f"unknown reviewed recording artifact: {recording['local_artifact']}")
        for media in data.get("external_media", []):
            if media["source"] not in source_ids:
                raise SystemExit(f"unknown external media source: {media['source']}")
        modern_editions = []
        for edition_record in sorted((directory / "editions").glob("*/EDITION.toml")):
            edition = tomllib.loads(edition_record.read_text())
            for witness in edition.get("witnesses", []):
                if witness["source_id"] not in source_ids:
                    raise SystemExit(
                        f"unknown source in {edition_record.relative_to(ROOT)} witness {witness['id']}: "
                        f"{witness['source_id']}"
                    )
                unknown = set(witness["artifact_ids"]) - artifact_ids
                if unknown:
                    raise SystemExit(
                        f"unknown artifact(s) in {edition_record.relative_to(ROOT)} witness {witness['id']}: "
                        f"{', '.join(sorted(unknown))}"
                    )
            edition["directory"] = edition_record.parent
            modern_editions.append(edition)
        data["modern_editions"] = modern_editions
        entries.append((directory, data))
    return entries


def render_song(data):
    source_number = {source["id"]: index for index, source in enumerate(data["sources"], 1)}
    source_by_id = {source["id"]: source for source in data["sources"]}
    artifact_by_id = {artifact["id"]: artifact for artifact in data["artifacts"]}
    lines = [GENERATED, "", f"# {data['title']} — {', '.join(data['creators'])}", "", data["summary"]]
    if data.get("modern_editions"):
        lines += ["", "## Modern editions", ""]
        for record in data["modern_editions"]:
            edition = record["edition"]
            outputs = record["outputs"]
            edition_path = f"./editions/{edition['id']}"
            lines += [
                f"### {edition['title']}",
                "",
                f"**{edition['status'].replace('-', ' ').title()}** — transcribed and engraved by {edition['transcriber']}. "
                f"Current scope: {edition['current_scope']}. "
                f"Dedicated under [{edition['license']}]({edition['license_url']}).",
                "",
                f"[MusicXML]({edition_path}/{outputs['musicxml']}) · "
                f"[MuseScore]({edition_path}/{outputs['musescore']}) · "
                f"[edition manifest]({edition_path}/EDITION.toml)",
            ]
    lines += ["", "## Files", ""]
    for artifact in data["artifacts"]:
        source = source_number[artifact["acquired_from"]]
        relationship = f"; derived from `{artifact['derived_from']}` ({artifact['derivation']})" if artifact.get("derived_from") else ""
        lines.append(f"- [{artifact['label']}](./inputs/{artifact['file']}) — SHA-256 `{artifact['sha256']}`; acquired from [S{source}](#source-s{source}){relationship}.")
    lines += ["", "## Research record", "", f"Research conducted: {data['research_date']}. Every URL used as evidence is listed below with its retrieval date and external archive links when available.", "", "## Documented facts", ""]
    for fact in data["facts"]:
        citations = " ".join(f"[S{source_number[source]}](#source-s{source_number[source]})" for source in fact["sources"])
        lines.append(f"- {fact['text']} {citations}")
    if data.get("reviewed_recordings"):
        lines += ["", "## Reviewed public-domain recordings", "", "These recordings are documented as public domain in the United States.", ""]
        for recording in data["reviewed_recordings"]:
            source = source_number[recording["source"]]
            links = [f"[source record](#source-s{source})"]
            if recording.get("local_artifact"):
                artifact = artifact_by_id[recording["local_artifact"]]
                links.insert(0, f"[local audio](./inputs/{artifact['file']})")
            elif source_by_id[recording["source"]].get("download_url"):
                links.insert(0, f"[source WAV]({source_by_id[recording['source']]['download_url']})")
            note = f" — {recording['note']}" if recording.get("note") else ""
            lines.append(f"- **{recording['performer']}** — {recording['date']} — {' · '.join(links)}{note}")
    if data.get("external_media"):
        lines += ["", "## Watch a performance", ""]
        for media in data["external_media"]:
            source = source_number[media["source"]]
            lines.append(f"- [{media['title']}]({media['url']}) — {media['rights_note']} [S{source}](#source-s{source})")
    if data.get("creative_commons_works"):
        lines += ["", "## Creative Commons adaptations", ""]
        for work in data["creative_commons_works"]:
            source = source_number[work["source"]]
            files = ", ".join(
                f"[{artifact_by_id[artifact_id]['label']}](./inputs/{artifact_by_id[artifact_id]['file']})"
                for artifact_id in work["files"]
            )
            lines.append(
                f"- **{work['title']}** ({work['date']}) by {work['creator']} — "
                f"[{work['license_name']}]({work['license_url']}); {files}. "
                f"{work['note']} [S{source}](#source-s{source})"
            )
    lines += ["", "## Rights note", "", data["rights_note"], "", "## Sources", ""]
    for index, source in enumerate(data["sources"], 1):
        links = f"[live page]({source['url']})"
        if source.get("wayback_url"):
            links += f" · [Wayback snapshot]({source['wayback_url']})"
        if source.get("archive_today_url"):
            links += f" · [archive.today snapshot]({source['archive_today_url']})"
        lines += [f'<a id="source-s{index}"></a>', "", f"### S{index}. {source['title']}", "", f"- {links}", f"- Retrieved: {source['retrieved']}"]
        if source.get("download_url"):
            artifact = next((item for item in data["artifacts"] if item["acquired_from"] == source["id"]), None)
            saved = f" · [saved artifact](./inputs/{artifact['file']})" if artifact else ""
            lines.append(f"- [Artifact download URL]({source['download_url']}){saved}")
        if source.get("rights"):
            rights = f"[{source['rights']}]({source['rights_url']})" if source.get("rights_url") else source["rights"]
            lines.append(f"- Rights: {rights}")
        if source.get("attribution"):
            lines.append(f"- Attribution: {source['attribution']}")
        if source.get("snapshot_note"):
            lines.append(f"- Note: {source['snapshot_note']}")
        lines.append("")
    if data.get("leads"):
        lines += ["## Unreviewed research leads", "", "These URLs have been collected and queued for preservation, but do not yet support any documented fact.", ""]
        for lead in data["leads"]:
            lines.append(f"- [{lead['url']}]({lead['url']}) — added {lead['added']}; status: {lead['status']}")
        lines.append("")
    if data.get("listening", {}).get("urls"):
        lines += ["## Hear other recordings", "", data["listening"]["note"], ""]
        for url in data["listening"]["urls"]:
            label = url.rstrip("/").rsplit("/", 1)[-1]
            lines.append(f"- [`{label}`]({url})")
        lines.append("")
    lines += ["## Provenance model", "", "[`inputs/CREDITS.toml`](./inputs/CREDITS.toml) is the canonical source manifest and archival queue. [`inputs/`](./inputs/) contains the downloaded media artifacts. Complete web-page snapshots are linked from external archival services rather than stored locally. This README is a derivative build; run `python3 scripts/build.py` from the repository root after changing canonical inputs.", "", "[Back to the shelf](../../README.md)", ""]
    return "\n".join(lines)


def render_index(entries):
    lines = [GENERATED, "", "# Piano score shelf", "", "A small, manually curated shelf of piano scores and reference recordings for study. The collection can grow in any musical direction without a fixed genre taxonomy.", "", "## Scores", ""]
    for directory, data in entries:
        lines.append(f"- [{data['title']} — {', '.join(data['creators'])}]({directory.relative_to(ROOT).as_posix()}/README.md)")
    lines += ["", "## Evidence and reproducibility", "", "Every song keeps a canonical `inputs/CREDITS.toml` and checksummed downloaded artifacts under `inputs/`. The manifest states the research date, original URLs, retrieval dates, supported facts, and external archive links. It also acts as the queue for archival automation.", "", "The public README files are generated derivatives. After changing canonical inputs, rebuild them with:", "", "```sh", "python3 scripts/build.py", "```", "", "Use `python3 scripts/build.py --check` to verify checksums and confirm that generated pages are current.", "", "## Adding a song", "", "1. Create `songs/<slug>/inputs/` and copy [`templates/CREDITS.toml`](templates/CREDITS.toml) into it.", "2. Put every consulted URL in the manifest and keep downloaded scores and recordings in `inputs/`.", "3. Record research and retrieval dates, artifact checksums, supported facts, rights conclusions, and returned archive URLs.", "4. Run `python3 scripts/archive_urls.py --list` to inspect the archival queue, then submit it with `--wayback` when ready.", "5. Add returned Wayback URLs to `CREDITS.toml`. Add `archive_today_url` manually when using archive.today, which has no stable official submission API.", "6. Run `python3 scripts/build.py`, review the generated pages, then run `python3 scripts/build.py --check`.", "", "## Rights", "", "Each entry documents the evidence used to assess its composition, edition, recording, and file. Copyright status outside the United States may differ. There is no repository-wide license for the collected artifacts.", ""]
    return "\n".join(lines)


def render_site_song(data):
    slug = data["slug"]
    source_number = {source["id"]: index for index, source in enumerate(data["sources"], 1)}
    source_by_id = {source["id"]: source for source in data["sources"]}
    artifact_by_id = {artifact["id"]: artifact for artifact in data["artifacts"]}
    audio_items = []
    for recording in sorted(data.get("reviewed_recordings", []), key=lambda item: item["date"]):
        if not recording.get("local_artifact"):
            continue
        primary = artifact_by_id[recording["local_artifact"]]
        related = [artifact for artifact in data["artifacts"] if artifact["acquired_from"] == primary["acquired_from"]]
        wav = next((artifact for artifact in related if artifact["file"].lower().endswith(".wav")), None)
        mp3 = next((artifact for artifact in related if artifact["file"].lower().endswith(".mp3")), None)
        label = f"{recording['performer']} ({recording['date'][:4]})"
        audio_items.append((label, wav, mp3))
    listening = data.get("listening", {})
    listening_ids = [url.rstrip("/").rsplit("/", 1)[-1] for url in listening.get("urls", [])]
    listening_labels = listening.get("labels", [])
    duplicate_labels = {label for label in listening_labels if listening_labels.count(label) > 1}
    score_editions = []
    for edition in data.get("score_editions", []):
        images = [artifact_by_id[artifact_id] for artifact_id in edition["artifacts"]]
        score_editions.append((edition, images))
    arrangements = []
    for arrangement in data.get("arrangements", []):
        images = [artifact_by_id[artifact_id] for artifact_id in arrangement["artifacts"]]
        arrangements.append((arrangement, images))
    cc_works = []
    for work in data.get("creative_commons_works", []):
        files = [artifact_by_id[artifact_id] for artifact_id in work["files"]]
        images = [artifact_by_id[artifact_id] for artifact_id in work.get("images", [])]
        audio = artifact_by_id[work["audio"]] if work.get("audio") else None
        cc_works.append((work, files, images, audio))
    modern_editions = []
    for record in data.get("modern_editions", []):
        edition = record["edition"]
        outputs = record["outputs"]
        base = f"songs/{slug}/editions/{edition['id']}"
        modern_editions.append(
            {
                "title": edition["title"],
                "status": edition["status"].replace("-", " ").title(),
                "transcriber": edition["transcriber"],
                "scope": edition["current_scope"],
                "license": edition["license"],
                "license_url": edition["license_url"],
                "musicxml_path": f"{base}/{outputs['musicxml']}",
                "musescore_path": f"{base}/{outputs['musescore']}",
                "manifest_path": f"{base}/EDITION.toml",
            }
        )
    lines = [
        "+++",
        f"title = {json.dumps(data['title'])}",
        f"description = {json.dumps(data['summary'])}",
        'template = "song.html"',
        f"path = {json.dumps('songs/' + slug)}",
        "[extra]",
        f"creators = {json.dumps(data['creators'])}",
        f"has_reviewed_recordings = {'true' if data.get('reviewed_recordings') else 'false'}",
        f"has_unreviewed_leads = {'true' if data.get('leads') else 'false'}",
        "modern_editions = [",
        *[
            "  { " + ", ".join(f"{key} = {json.dumps(value)}" for key, value in edition.items()) + " },"
            for edition in modern_editions
        ],
        "]",
        "score_editions = [",
        *[
            "  { title = "
            + json.dumps(edition["title"])
            + ", note = "
            + json.dumps(edition["note"])
            + ", source_number = "
            + str(source_number[edition["source"]])
            + ", images = ["
            + ", ".join(
                "{ label = " + json.dumps(image["label"]) + ", path = "
                + json.dumps("songs/" + slug + "/inputs/" + image["file"]) + " }"
                for image in images
            )
            + "] },"
            for edition, images in score_editions
        ],
        "]",
        "arrangements = [",
        *[
            "  { title = "
            + json.dumps(arrangement["title"])
            + ", arranger = "
            + json.dumps(arrangement["arranger"])
            + ", instrumentation = "
            + json.dumps(arrangement["instrumentation"])
            + ", date = "
            + json.dumps(arrangement["date"])
            + ", note = "
            + json.dumps(arrangement["note"])
            + ", source_number = "
            + str(source_number[arrangement["source"]])
            + ", images = ["
            + ", ".join(
                "{ label = " + json.dumps(image["label"]) + ", path = "
                + json.dumps("songs/" + slug + "/inputs/" + image["file"]) + " }"
                for image in images
            )
            + "] },"
            for arrangement, images in arrangements
        ],
        "]",
        "creative_commons_works = [",
        *[
            "  { title = "
            + json.dumps(work["title"])
            + ", creator = "
            + json.dumps(work["creator"])
            + ", date = "
            + json.dumps(work["date"])
            + ", note = "
            + json.dumps(work["note"])
            + ", license_name = "
            + json.dumps(work["license_name"])
            + ", license_url = "
            + json.dumps(work["license_url"])
            + ", source_number = "
            + str(source_number[work["source"]])
            + ", files = ["
            + ", ".join(
                "{ label = " + json.dumps(file["label"]) + ", path = "
                + json.dumps("songs/" + slug + "/inputs/" + file["file"]) + " }"
                for file in files
            )
            + "], images = ["
            + ", ".join(
                "{ label = " + json.dumps(image["label"]) + ", path = "
                + json.dumps("songs/" + slug + "/inputs/" + image["file"]) + " }"
                for image in images
            )
            + "], audio_path = "
            + (json.dumps("songs/" + slug + "/inputs/" + audio["file"]) if audio else "false")
            + " },"
            for work, files, images, audio in cc_works
        ],
        "]",
        "audio_items = [",
        *[
            f"  {{ label = {json.dumps(label)}, wav_path = {json.dumps('songs/' + slug + '/inputs/' + wav['file']) if wav else 'false'}, mp3_path = {json.dumps('songs/' + slug + '/inputs/' + mp3['file']) if mp3 else 'false'} }},"
            for label, wav, mp3 in audio_items
        ],
        "]",
        f"listening_note = {json.dumps(listening.get('note', ''))}",
        "listening_items = [",
        *[
            f"  {{ identifier = {json.dumps(identifier)}, label = {json.dumps(label + (' — ' + identifier.rsplit('_', 1)[-1] if label in duplicate_labels else ''))} }},"
            for identifier, label in zip(listening_ids, listening_labels)
        ],
        "]",
        "external_media = [",
        *[
            f"  {{ title = {json.dumps(media['title'])}, url = {json.dumps(media['url'])}, rights_note = {json.dumps(media['rights_note'])} }},"
            for media in data.get("external_media", [])
        ],
        "]",
        "+++",
        "",
        data["summary"],
        "",
        "## Research record",
        "",
        f"Research conducted: {data['research_date']}.",
        "",
        "## Documented facts",
        "",
    ]
    for fact in data["facts"]:
        citations = " ".join(f"[S{source_number[item]}](#source-s{source_number[item]})" for item in fact["sources"])
        lines.append(f"- {fact['text']} {citations}")
    if data.get("reviewed_recordings"):
        artifact_by_id = {artifact["id"]: artifact for artifact in data["artifacts"]}
        lines += ["", "## Reviewed public-domain recordings", "", "These recordings are documented as public domain in the United States.", ""]
        for recording in data["reviewed_recordings"]:
            source = source_number[recording["source"]]
            links = [f"[source record](#source-s{source})"]
            if recording.get("local_artifact"):
                artifact = artifact_by_id[recording["local_artifact"]]
                links.insert(0, f"[local audio](inputs/{artifact['file']})")
            elif source_by_id[recording["source"]].get("download_url"):
                links.insert(0, f"[source WAV]({source_by_id[recording['source']]['download_url']})")
            note = f" — {recording['note']}" if recording.get("note") else ""
            lines.append(f"- **{recording['performer']}** — {recording['date']} — {' · '.join(links)}{note}")
    lines += ["", "## Rights note", "", data["rights_note"], "", "ARCHIVE_PLAYER_INSERTION_POINT_7D3E", "", "## Files", "", "| File | Source | SHA-256 |", "| --- | --- | --- |"]
    for artifact in data["artifacts"]:
        source = source_number[artifact["acquired_from"]]
        lines.append(f"| [{artifact['label']}](inputs/{artifact['file']}) | [S{source}](#source-s{source}) | `{artifact['sha256']}` |")
    lines += ["", "## Sources", ""]
    for index, source in enumerate(data["sources"], 1):
        links = [f"[live page]({source['url']})"]
        if source.get("wayback_url"):
            links.append(f"[Wayback snapshot]({source['wayback_url']})")
        if source.get("archive_today_url"):
            links.append(f"[archive.today snapshot]({source['archive_today_url']})")
        if source.get("download_url"):
            links.append(f"[source download]({source['download_url']})")
        lines += [f'<span id="source-s{index}"></span>', "", f"### S{index}. {source['title']}", "", " · ".join(links), "", f"Retrieved: {source['retrieved']}", ""]
        if source.get("rights"):
            rights = f"[{source['rights']}]({source['rights_url']})" if source.get("rights_url") else source["rights"]
            lines += [f"Rights: {rights}", ""]
        if source.get("attribution"):
            lines += [f"Attribution: {source['attribution']}", ""]
    if data.get("leads"):
        lines += ["## Unreviewed research leads", "", "Collected and queued for preservation; not yet used as evidence.", ""]
        for lead in data["leads"]:
            lines.append(f"- [{lead['url']}]({lead['url']}) — added {lead['added']}")
        lines.append("")
    lines += ["## Provenance", "", f"[CREDITS.toml](inputs/CREDITS.toml) is the canonical manifest for this generated page.", ""]
    return "\n".join(lines)


def build_site_inputs(entries, check):
    static_songs = ROOT / "static" / "songs"
    if not check:
        if static_songs.exists():
            shutil.rmtree(static_songs)
        static_songs.mkdir(parents=True)
    for directory, data in entries:
        slug = data["slug"]
        page = ROOT / "content" / "songs" / slug / "index.md"
        if not check:
            page.parent.mkdir(parents=True, exist_ok=True)
        write_or_check(page, render_site_song(data), check)
        target = static_songs / slug / "inputs"
        if not check:
            shutil.copytree(directory / "inputs", target)
        elif not target.exists():
            raise SystemExit(f"generated site inputs are missing: {target.relative_to(ROOT)}")
        for record in data.get("modern_editions", []):
            edition = record["edition"]
            outputs = record["outputs"]
            source = record["directory"]
            edition_target = static_songs / slug / "editions" / edition["id"]
            expected = ["EDITION.toml", outputs["musicxml"], outputs["musescore"]]
            if not check:
                edition_target.mkdir(parents=True, exist_ok=True)
                for filename in expected:
                    shutil.copy2(source / filename, edition_target / filename)
            elif any(not (edition_target / filename).exists() for filename in expected):
                raise SystemExit(f"generated site edition files are missing: {edition_target.relative_to(ROOT)}")


def write_or_check(path, content, check):
    if check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f"generated file is stale: {path.relative_to(ROOT)}")
    else:
        path.write_text(content)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    entries = load_entries()
    for directory, data in entries:
        write_or_check(directory / "README.md", render_song(data), args.check)
    write_or_check(ROOT / "README.md", render_index(entries), args.check)
    build_site_inputs(entries, args.check)


if __name__ == "__main__":
    main()
